<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="TaskManager.Api.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskManager.Application\TaskManager.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
  </ItemGroup>

</Project>
