<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TaskManager.Api.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskManager.Application\TaskManager.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.19.2" />
  </ItemGroup>

</Project>
